///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoinModel {
/*
{
  "15m": 130170.05,
  "last": 130170.05,
  "buy": 130170.05,
  "sell": 130170.05,
  "symbol": "BRL"
} 
*/

  double? the15m;
  double? last;
  double? buy;
  double? sell;
  String? symbol;

  CoinModel({
    this.the15m,
    this.last,
    this.buy,
    this.sell,
    this.symbol,
  });
  CoinModel.fromJson(Map<String, dynamic> json) {
    the15m = json['15m']?.toDouble();
    last = json['last']?.toDouble();
    buy = json['buy']?.toDouble();
    sell = json['sell']?.toDouble();
    symbol = json['symbol']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['15m'] = the15m;
    data['last'] = last;
    data['buy'] = buy;
    data['sell'] = sell;
    data['symbol'] = symbol;
    return data;
  }
}
